### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by systay** [davidrmiller/biosim4#15]
I love this project. Not so much C++. I can't find anything about license - would it be possible to add something about the license of this repo so we know what we can do with the code? I'm considering rewriting in golang.

**Comment by mmahmoudian** [comment]
This is interesting, I exactly came here to check the license as I am planning to write it in Python or R. The Youtube video was very inspiring, plus as a microbiologist and bioinformatician I believe this would be a nice way to make my mind think better.

**Comment by davidrmiller** [comment]
Added an MIT license. If that doesn't meet your specific needs, just let me know. Thanks for the kind words, and best of luck to @systay with golang and to @mmahmoudian with Python or R.

**Comment by systay** [comment]
👋 Started working on it over here, if anyone is interested: https://github.com/systay/gobiosim
