### ISSUE TITLE
How are duplicate synapses prevented?

### ISSUE THREAD

**Issue by FlorianSchroeter** [davidrmiller/biosim4#18]
Dear @davidrmiller,

first and foremost I want to thank you for all the time and effort you invested in both your inspiring video and this GitHub repository. A lot of questions are very well answered in the video and even more are answered by the comments in your source code. Well done. Thank you very much.

While implementing a WinForms application in C# with a simulation following your example I came to the conclusion that with a certain probability two genes could encode a connection between the same neurons. Hence there might be two equal connections with most likely different weights. I assume it would be of no issue if source and target of both connections were swapped as it could happen for internal neurons. But how do you prevent duplicate connections between the same source and target neuron or are such duplicates of no issue and just calculated as usual?

Kind regards,
Florian

Edit:
I might have found an answer to this question myself in the abstract of this paper: https://www.pnas.org/content/115/29/E6871

> Recent experimental studies suggest that, in cortical microcircuits of the mammalian brain, the majority of neuron-to-neuron connections are realized by multiple synapses.

**Comment by davidrmiller** [comment]
Thanks for the link to that paper -- it looks very interesting indeed.

In the simulator, the connections are processed in an order such that the weights get summed if there are multiple connections between two neurons. The internal neurons are a little more interesting. Their outputs are latched and connections between internal neurons are processed in the order in which they occur in the genome. They can form simple state machines. I would think that bi-directional connections between two internal neurons could potentially set up an oscillating feedback loop, but I've not thought deeply about it.

**Comment by FlorianSchroeter** [comment]
I see. So multiple connections between the same neurons are indeed possible, apparently computable and according to the paper might actually contribute to the simulation in a more or less natural way. Thanx.
