### ISSUE TITLE
Repeated  sensorVal message

### ISSUE THREAD

**Issue by venzen** [davidrmiller/biosim4#20]
Great video and good idea to make the code open source .

Successfully compiled from the instructions in the README file using the _docker_ image.

For the initial hundred or so generations of most sims I run, this message repeats verbosely:

```sensorVal=-2147483648 for genetic similarity fwd```

Do most users experience this or is it perhaps due to a wayward parameter ?

I'm not seeing repeat messages other than this particular value and genetic similarity "fwd".

**Comment by davidrmiller** [comment]
I received a report of this from another person, so there must be a bug in genomeSimilarity() in src/genome-compare.cpp. The configuration parameter genomeComparisonMethod in biosim4.ini determines which of three different comparison methods are used. The default is the function hammingDistanceBits(). For now, one way to proceed is to compile the program without that sensor by moving the enumerant GENETIC_SIM_FWD in src/sensors-actions.h.

**Comment by venzen** [comment]
Thank you for the reply.

I notice in _getSensors.cpp_ that ```lastMoveDir``` is called without any attribute:

```
    case Sensor::SIGNAL0_FWD:
        // Sense signal0 density along axis of last movement direction
        sensorVal = getSignalDensityAlongAxis(0, loc, lastMoveDir);
        break;
    case Sensor::SIGNAL0_LR:
        // Sense signal0 density along an axis perpendicular to last movement direction
        sensorVal = getSignalDensityAlongAxis(0, loc, lastMoveDir.rotate90DegCW());
        break;
```

Is this intentional and correct?

**Comment by davidrmiller** [comment]
@venzen, I noticed that sensorVal is not initialized when allocated in getSensor() and can return with an undefined value from getSensor(). I modified src/getSensor.cpp to fix that. Can you test if that helps?

**Comment by venzen** [comment]
Initializing ```sensorVal``` fixes it! I've run several quick sims and a larger resource-heavy sim without the issue recurring. You can close PR #21.
