### ISSUE TITLE
  does not compile on ARM64 architecture

### ISSUE THREAD

**Issue by tigercoding56** [davidrmiller/biosim4#42]
i thought it would be a good use for a raspberry pi with manjaro Linux  currently installed on it to run this for a few days   and then i could see the result but  /lib/x84_64 or /bin/x84_64 or something like that was not found      

maybe you could eventually add support for foreign CPU  architectures

**Comment by venzen** [comment]
@tigercoding56 Have you tried using the Docker image instead? The README has instructions about building and running the project in a docker container.

**Comment by mathematicalmichael** [comment]
@tigercoding56 I validated this compiles and runs just fine on a raspi using the arm-based docker image that I published to `mindthegrows/biosim4`: https://hub.docker.com/r/mindthegrow/biosim4/tags. If you want to know DIY without docker, you can reference the `Dockerfile` in this repo and install the same libs from your package manager (be aware they may have slightly different names).

My POV on this is: use whatever OS you want to, but when it comes to software, lean on docker as much as possible to give you reproducible compilation/build environments.

**Comment by tigercoding56** [comment]
i should have named this issue does not compile on ARM64 architecture using cmake instead  ....    
i will try using docker
