### ISSUE TITLE
getSignalDensityAlongAxis uses the wrong radius parameter

### ISSUE THREAD

**Issue by jeremy-pereira** [davidrmiller/biosim4#46]
in [getSensor.cpp](https://github.com/davidrmiller/biosim4/blob/main/src/getSensor.cpp), line 138 in `getSignalDensityAlongAxis ()` https://github.com/davidrmiller/biosim4/blob/0bcc5fb350f01ea46473b0c9ca7a141970b7ac0c/src/getSensor.cpp#L138 the sensor radius is given as `p.populationSensorRadius `. It should be using `p.signalSensorRadius`

**Comment by davidrmiller** [comment]
Thanks for spotting that, I'll fix it.

**Comment by davidrmiller** [comment]
Fixed in main.
