### ISSUE TITLE
suse error

### ISSUE THREAD

**Issue by sychris** [davidrmiller/biosim4#6]
First let me start by saying i have very little experience in linux atempted to get running from suse
cimg-devel version 2.9.7
libopencv-devel version 4.5.2
gcc10 10.3.1

attempted make failed with the following.

sychris@localhost:~/Downloads/biosim4-main> make
test -d bin/Debug || mkdir -p bin/Debug
test -d obj/Debug/src || mkdir -p obj/Debug/src
g++ -Wall -fexceptions -g -fopenmp -I/usr/include/opencv4 -c src/signals.cpp -o obj/Debug/src/signals.o
g++ -Wall -fexceptions -g -fopenmp -I/usr/include/opencv4 -c src/main.cpp -o obj/Debug/src/main.o
g++ -Wall -fexceptions -g -fopenmp -I/usr/include/opencv4 -c src/params.cpp -o obj/Debug/src/params.o
g++ -Wall -fexceptions -g -fopenmp -I/usr/include/opencv4 -c src/peeps.cpp -o obj/Debug/src/peeps.o
g++ -Wall -fexceptions -g -fopenmp -I/usr/include/opencv4 -c src/random.cpp -o obj/Debug/src/random.o
g++ -Wall -fexceptions -g -fopenmp -I/usr/include/opencv4 -c src/simulator.cpp -o obj/Debug/src/simulator.o
g++ -Wall -fexceptions -g -fopenmp -I/usr/include/opencv4 -c src/spawnNewGeneration.cpp -o obj/Debug/src/spawnNewGeneration.o
g++ -Wall -fexceptions -g -fopenmp -I/usr/include/opencv4 -c src/survival-criteria.cpp -o obj/Debug/src/survival-criteria.o
g++ -Wall -fexceptions -g -fopenmp -I/usr/include/opencv4 -c src/unitTestBasicTypes.cpp -o obj/Debug/src/unitTestBasicTypes.o
g++ -Wall -fexceptions -g -fopenmp -I/usr/include/opencv4 -c src/unitTestConnectNeuralNetWiringFromGenome.cpp -o obj/Debug/src/unitTestConnectNeuralNetWiringFromGenome.o
g++ -Wall -fexceptions -g -fopenmp -I/usr/include/opencv4 -c src/unitTestGridVisitNeighborhood.cpp -o obj/Debug/src/unitTestGridVisitNeighborhood.o
g++ -Wall -fexceptions -g -fopenmp -I/usr/include/opencv4 -c src/genome-compare.cpp -o obj/Debug/src/genome-compare.o
g++ -Wall -fexceptions -g -fopenmp -I/usr/include/opencv4 -c src/analysis.cpp -o obj/Debug/src/analysis.o
g++ -Wall -fexceptions -g -fopenmp -I/usr/include/opencv4 -c src/basicTypes.cpp -o obj/Debug/src/basicTypes.o
g++ -Wall -fexceptions -g -fopenmp -I/usr/include/opencv4 -c src/createBarrier.cpp -o obj/Debug/src/createBarrier.o
g++ -Wall -fexceptions -g -fopenmp -I/usr/include/opencv4 -c src/endOfGeneration.cpp -o obj/Debug/src/endOfGeneration.o
g++ -Wall -fexceptions -g -fopenmp -I/usr/include/opencv4 -c src/endOfSimStep.cpp -o obj/Debug/src/endOfSimStep.o
g++ -Wall -fexceptions -g -fopenmp -I/usr/include/opencv4 -c src/executeActions.cpp -o obj/Debug/src/executeActions.o
g++ -Wall -fexceptions -g -fopenmp -I/usr/include/opencv4 -c src/feedForward.cpp -o obj/Debug/src/feedForward.o
g++ -Wall -fexceptions -g -fopenmp -I/usr/include/opencv4 -c src/genome.cpp -o obj/Debug/src/genome.o
g++ -Wall -fexceptions -g -fopenmp -I/usr/include/opencv4 -c src/getSensor.cpp -o obj/Debug/src/getSensor.o
g++ -Wall -fexceptions -g -fopenmp -I/usr/include/opencv4 -c src/grid.cpp -o obj/Debug/src/grid.o
g++ -Wall -fexceptions -g -fopenmp -I/usr/include/opencv4 -c src/imageWriter.cpp -o obj/Debug/src/imageWriter.o
g++ -Wall -fexceptions -g -fopenmp -I/usr/include/opencv4 -c src/indiv.cpp -o obj/Debug/src/indiv.o
g++  -o bin/Debug/biosim4 obj/Debug/src/signals.o obj/Debug/src/main.o obj/Debug/src/params.o obj/Debug/src/peeps.o obj/Debug/src/random.o obj/Debug/src/simulator.o obj/Debug/src/spawnNewGeneration.o obj/Debug/src/survival-criteria.o obj/Debug/src/unitTestBasicTypes.o obj/Debug/src/unitTestConnectNeuralNetWiringFromGenome.o obj/Debug/src/unitTestGridVisitNeighborhood.o obj/Debug/src/genome-compare.o obj/Debug/src/analysis.o obj/Debug/src/basicTypes.o obj/Debug/src/createBarrier.o obj/Debug/src/endOfGeneration.o obj/Debug/src/endOfSimStep.o obj/Debug/src/executeActions.o obj/Debug/src/feedForward.o obj/Debug/src/genome.o obj/Debug/src/getSensor.o obj/Debug/src/grid.o obj/Debug/src/imageWriter.o obj/Debug/src/indiv.o  -lX11 -lpthread -fopenmp /usr/lib/x86_64-linux-gnu/libopencv_core.so /usr/lib/x86_64-linux-gnu/libopencv_video.so /usr/lib/x86_64-linux-gnu/libopencv_videoio.so
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: cannot find /usr/lib/x86_64-linux-gnu/libopencv_core.so: No such file or directory
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: cannot find /usr/lib/x86_64-linux-gnu/libopencv_video.so: No such file or directory
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: cannot find /usr/lib/x86_64-linux-gnu/libopencv_videoio.so: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:60: out_debug] Error 1

**Comment by sychris** [comment]
update was able to get it to compile by installing the codeblocks ide. then going to project, build options, linker settings and changing the linked libraries to usr/lib64 where suse installed them. however i am now getting a ton of errors when i try to run the program all related to opencv GStreamer

**Comment by davidrmiller** [comment]
@sychris, I'm impressed you got so much working on SUSE. Unfortunately, SUSE and the GStreamer warnings you are getting are outside of my area of expertise. Perhaps some other readers can offer suggestions for how to proceed.

**Comment by mathematicalmichael** [comment]
@sychris if you're still struggling, might I suggest installing docker and trying the process in #8? I have had to work across many distributions and docker has been my saving grace for making the OS irrelevant to running software.

**Comment by venzen** [comment]
@sychris. I would recommend that, as a new Linux user, you install Ubuntu Linux and install Docker as described here: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-20-04

These instructions should work for Ubuntu 21.10 (worked for me on version 18.04). Then pull the Docker image for this project. This is definitely the most efficient and salient way to go - both with this project and with Linux in general.

**Comment by sychris** [comment]
to be honest I've moved on and was just willing to give it a try in suse as that is what I had available not really willing to reinstall my OS to play around with the software but I think you for your recommendations they could very well help out the next person :)
