### ISSUE TITLE
Internal node clarification

### ISSUE THREAD

**Issue by TheLumbee** [davidrmiller/biosim4#73]
You mention in the video during the "Eastern Half Survival" if you will, that the internal node somehow computes whether to drive the MvE neuron or the  Mrn neuron, as if there are calculations beside the weighted inputs and activation function occurring in the internal node.

For clarification, I wonder if that was the case. I didn't see anything like that in the code. From what I can tell, the Mrn neuron gets the same inputs every step from the internal node, but when the LPf neuron isn't further driving the MvE neuron then the Mrn neuron is executed. Is that correct? Or is the internal node actually doing something else when the MvE neuron is activated.

Thanks for any clarification.

**Comment by davidrmiller** [comment]
Ah, I think you're right. Your description more accurately describes how that network works. Thanks for making that observation.

**Comment by TheLumbee** [comment]
@davidrmiller Thanks for the response and clarification. I was just a little confused. You've really inspired me to implement this in some of my projects. Also, thanks for providing the world with your code and this knowledge. Keep up the great work!
