### ISSUE TITLE
getSignalDensityAlongAxis() uses wrong coordinates when calling getMagnitude()

### ISSUE THREAD

**Issue by osechet** [davidrmiller/biosim4#84]
In `getSignalDensityAlongAxis()`: https://github.com/davidrmiller/biosim4/blob/ee9505a281b0341fd4aacacb29592138a52b5f52/src/getSensor.cpp#L132

The coordinates passed to the `getMagnitude()` function should be `tloc`, not `loc`.

**Comment by davidrmiller** [comment]
Thanks for reporting this. I'll verify then update the code. Good catch!
